### ISSUE TITLE
十分感谢

### ISSUE THREAD

**Issue by jly8866** [ada012/docker-archer#3]
十分感谢dockerfile作者，不过有两个问题：
1.如何定期保持跟archer官方代码的同步呢
2.可否把archer官网地址挂在readme里

**Comment by chanyying** [comment]
@jly8866 
[archer](https://github.com/jly8866/archer)
我们有自己的archer维护，都会同步到docker-archer里面，是在archer的基础上做了很多优化，内部通过git submodule进行管理
